# Generated by Django 4.0.2 on 2022-04-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Emp_ID', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('Resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
